Table	Create Table
Bid	CREATE TABLE `Bid` (\n  `bid_id` int(11) NOT NULL AUTO_INCREMENT,\n  `alumni_id` int(11) NOT NULL,\n  `slot_id` int(11) NOT NULL,\n  `bid_amount` decimal(10,2) NOT NULL,\n  `status` varchar(20) DEFAULT 'ACTIVE',\n  `created_at` timestamp NULL DEFAULT current_timestamp(),\n  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),\n  PRIMARY KEY (`bid_id`),\n  UNIQUE KEY `unique_alumni_slot` (`alumni_id`,`slot_id`),\n  KEY `slot_id` (`slot_id`),\n  CONSTRAINT `bid_ibfk_1` FOREIGN KEY (`slot_id`) REFERENCES `Slot` (`slot_id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
Slot	CREATE TABLE `Slot` (\n  `slot_id` int(11) NOT NULL AUTO_INCREMENT,\n  `slot_date` date NOT NULL,\n  `bidding_start_time` datetime NOT NULL,\n  `bidding_end_time` datetime NOT NULL,\n  `status` varchar(20) DEFAULT 'OPEN',\n  `created_at` timestamp NULL DEFAULT current_timestamp(),\n  PRIMARY KEY (`slot_id`),\n  UNIQUE KEY `slot_date` (`slot_date`)\n) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
Slot_Result	CREATE TABLE `Slot_Result` (\n  `result_id` int(11) NOT NULL AUTO_INCREMENT,\n  `slot_id` int(11) NOT NULL,\n  `winning_bid_id` int(11) NOT NULL,\n  `selected_at` timestamp NULL DEFAULT current_timestamp(),\n  `winning_alumni_id` int(11) DEFAULT NULL,\n  PRIMARY KEY (`result_id`),\n  KEY `slot_id` (`slot_id`),\n  KEY `winning_bid_id` (`winning_bid_id`),\n  CONSTRAINT `slot_result_ibfk_1` FOREIGN KEY (`slot_id`) REFERENCES `Slot` (`slot_id`),\n  CONSTRAINT `slot_result_ibfk_2` FOREIGN KEY (`winning_bid_id`) REFERENCES `Bid` (`bid_id`)\n) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
alumni	CREATE TABLE `alumni` (\n  `alumni_id` int(11) NOT NULL AUTO_INCREMENT,\n  `user_id` int(11) NOT NULL,\n  `is_active_winner` tinyint(1) DEFAULT 0,\n  `profile_completion_status` varchar(50) DEFAULT NULL,\n  PRIMARY KEY (`alumni_id`),\n  UNIQUE KEY `unique_user_alumni` (`user_id`),\n  CONSTRAINT `alumni_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
alumni_profiles	CREATE TABLE `alumni_profiles` (\n  `profile_id` int(10) unsigned NOT NULL AUTO_INCREMENT,\n  `alumni_id` int(10) unsigned NOT NULL,\n  `degrees` text DEFAULT NULL,\n  `certifications` text DEFAULT NULL,\n  `licenses` text DEFAULT NULL,\n  `professional_courses` text DEFAULT NULL,\n  `employment_history` text DEFAULT NULL,\n  `profile_image` varchar(255) DEFAULT NULL,\n  `linkedin_url` varchar(255) DEFAULT NULL,\n  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),\n  PRIMARY KEY (`profile_id`),\n  KEY `alumni_id` (`alumni_id`)\n) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
Table	Create Table
api_logs	CREATE TABLE `api_logs` (\n  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,\n  `client_id` varchar(255) NOT NULL,\n  `endpoint` varchar(255) NOT NULL,\n  `created_at` datetime NOT NULL DEFAULT current_timestamp(),\n  `status` smallint(6) NOT NULL,\n  `ip_address` varchar(45) NOT NULL,\n  PRIMARY KEY (`id`),\n  KEY `idx_api_logs_client_id` (`client_id`),\n  KEY `idx_api_logs_created_at` (`created_at`),\n  KEY `idx_api_logs_endpoint` (`endpoint`)\n) ENGINE=InnoDB AUTO_INCREMENT=521 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
developer	CREATE TABLE `developer` (\n  `developer_id` int(11) NOT NULL AUTO_INCREMENT,\n  `user_id` int(11) NOT NULL,\n  PRIMARY KEY (`developer_id`),\n  UNIQUE KEY `unique_user_developer` (`user_id`),\n  CONSTRAINT `developer_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
monthly_limit	CREATE TABLE `monthly_limit` (\n  `id` int(11) NOT NULL AUTO_INCREMENT,\n  `alumni_id` int(11) NOT NULL,\n  `month` int(11) DEFAULT NULL,\n  `year` int(11) NOT NULL,\n  `wins_count` int(11) DEFAULT 0,\n  `max_limit` int(11) DEFAULT 3,\n  PRIMARY KEY (`id`),\n  UNIQUE KEY `unique_alumni_month` (`alumni_id`,`month`,`year`)\n) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
rate_limit	CREATE TABLE `rate_limit` (\n  `ip_address` varchar(45) NOT NULL,\n  `endpoint` varchar(100) NOT NULL,\n  `requests` int(11) DEFAULT 1,\n  `last_reset` timestamp NULL DEFAULT current_timestamp(),\n  PRIMARY KEY (`ip_address`,`endpoint`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci
Table	Create Table
students	CREATE TABLE `students` (\n  `student_id` int(11) NOT NULL AUTO_INCREMENT,\n  `user_id` int(11) NOT NULL,\n  PRIMARY KEY (`student_id`),\n  UNIQUE KEY `unique_user_students` (`user_id`),\n  CONSTRAINT `students_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
user_api_tokens	CREATE TABLE `user_api_tokens` (\n  `token_id` int(11) NOT NULL AUTO_INCREMENT,\n  `user_id` int(11) NOT NULL,\n  `api_token` varchar(64) NOT NULL,\n  `expires_at` datetime NOT NULL,\n  `created_at` datetime DEFAULT current_timestamp(),\n  PRIMARY KEY (`token_id`),\n  KEY `user_id` (`user_id`),\n  CONSTRAINT `user_api_tokens_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
user_password_resets	CREATE TABLE `user_password_resets` (\n  `reset_id` int(11) NOT NULL AUTO_INCREMENT,\n  `user_id` int(11) NOT NULL,\n  `otp` varchar(6) DEFAULT NULL,\n  `otp_expires_at` datetime DEFAULT NULL,\n  `reset_token` varchar(64) DEFAULT NULL,\n  `reset_token_expires_at` datetime DEFAULT NULL,\n  `created_at` datetime DEFAULT current_timestamp(),\n  PRIMARY KEY (`reset_id`),\n  KEY `fk_user_password_resets_user` (`user_id`),\n  CONSTRAINT `fk_user_password_resets_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE CASCADE\n) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
Table	Create Table
users	CREATE TABLE `users` (\n  `user_id` int(11) NOT NULL AUTO_INCREMENT,\n  `user_name` varchar(150) NOT NULL,\n  `password_hash` varchar(255) NOT NULL,\n  `role` varchar(50) NOT NULL,\n  `email_verified` tinyint(1) DEFAULT 0,\n  `created_at` timestamp NULL DEFAULT current_timestamp(),\n  `first_name` varchar(100) DEFAULT NULL,\n  `second_name` varchar(100) DEFAULT NULL,\n  `date_of_birth` date DEFAULT NULL,\n  `phone_number` varchar(20) DEFAULT NULL,\n  `verification_token` varchar(100) DEFAULT NULL,\n  PRIMARY KEY (`user_id`),\n  UNIQUE KEY `email` (`user_name`)\n) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci
